### ISSUE TITLE
Docs Suggestion: Example section introductions

### ISSUE THREAD

**Issue by tylerflex** [flexcompute/autoflex#10]
Kind of a minor comment but I think it will improve the docs a bit.

For each of our docs sections, there is a page with a bunch of links to the specific notebooks. For example, in the "design space exploration" section, it looks like this

https://docs.flexcompute.com/projects/tidy3d/en/v2.6.0rc1/notebooks/docs/features/parameter_sweep.html

I think what would improve things a bit is to put a few paragraphs of introduction on this page, explaining what these examples are showing and which ones might be best to check out depending on what you want to do. For example, this page could include some text above the example links like:

"
Tidy3D offers a few tools that facilitate and automate the exploration of a user-defined design space. The `design` plugin is a wrapper that allows users to define a general "parameter space" and sample this space through tidy3d simulations. The result is returned to the user in a `pandas.DataFrame` format for easy post processing and analysis. For a detailed tutorial, see [Design Plugin Tutorial Link].  We also have tools for batch processing of simulations, which can make custom parameter sweeps convenient. For an example of batching simulations and other tools for managing the results in a more custom way, see the [Parameter Sweep Tutorial Link] example.
"

we can also address a few other improvements here, such as describing the limitations of the various features, or linking to the feature README.md for more information.

**Comment by FilipeFcp** [comment]
@tomflexcompute I finished writing the introduction texts. If you want to, take a look to see if the content and style are appropriate.

**Comment by daquinteroflex** [comment]
@FilipeFcp would you be able to send them to me?
